/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Homes */
        get: operations["list_homes_homes_get"];
        put?: never;
        /** Create Home */
        post: operations["create_home_homes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes/{home_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home */
        get: operations["get_home_homes__home_id__get"];
        put?: never;
        post?: never;
        /** Delete Home */
        delete: operations["delete_home_homes__home_id__delete"];
        options?: never;
        head?: never;
        /** Update Home */
        patch: operations["update_home_homes__home_id__patch"];
        trace?: never;
    };
    "/homes/{home_id}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Areas */
        get: operations["list_areas_homes__home_id__areas_get"];
        put?: never;
        /** Create Area */
        post: operations["create_area_homes__home_id__areas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{area_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Area */
        delete: operations["delete_area_areas__area_id__delete"];
        options?: never;
        head?: never;
        /** Update Area */
        patch: operations["update_area_areas__area_id__patch"];
        trace?: never;
    };
    "/homes/{home_id}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rooms */
        get: operations["list_rooms_homes__home_id__rooms_get"];
        put?: never;
        /** Create Room */
        post: operations["create_room_homes__home_id__rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_rooms__room_id__get"];
        put?: never;
        post?: never;
        /** Delete Room */
        delete: operations["delete_room_rooms__room_id__delete"];
        options?: never;
        head?: never;
        /** Update Room */
        patch: operations["update_room_rooms__room_id__patch"];
        trace?: never;
    };
    "/rooms/{room_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Device In Room */
        post: operations["create_device_in_room_rooms__room_id__devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes/{home_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_homes__home_id__devices_get"];
        put?: never;
        /** Create Device In Home */
        post: operations["create_device_in_home_homes__home_id__devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_devices__device_id__get"];
        put?: never;
        post?: never;
        /** Delete Device */
        delete: operations["delete_device_devices__device_id__delete"];
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_devices__device_id__patch"];
        trace?: never;
    };
    "/devices/{device_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Device Tasks */
        get: operations["list_device_tasks_devices__device_id__tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_devices__device_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes/{home_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Home Tasks */
        get: operations["list_home_tasks_homes__home_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_tasks__task_id__patch"];
        trace?: never;
    };
    "/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task Endpoint */
        post: operations["complete_task_endpoint_tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Device Logs */
        get: operations["list_device_logs_devices__device_id__logs_get"];
        put?: never;
        /** Create Device Log */
        post: operations["create_device_log_devices__device_id__logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes/{home_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Home Logs */
        get: operations["list_home_logs_homes__home_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes/{home_id}/consumables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consumables */
        get: operations["list_consumables_homes__home_id__consumables_get"];
        put?: never;
        /** Create Consumable */
        post: operations["create_consumable_homes__home_id__consumables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consumables/{consumable_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consumable */
        get: operations["get_consumable_consumables__consumable_id__get"];
        put?: never;
        post?: never;
        /** Delete Consumable */
        delete: operations["delete_consumable_consumables__consumable_id__delete"];
        options?: never;
        head?: never;
        /** Update Consumable */
        patch: operations["update_consumable_consumables__consumable_id__patch"];
        trace?: never;
    };
    "/tasks/{task_id}/consumables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task Consumables */
        get: operations["list_task_consumables_tasks__task_id__consumables_get"];
        put?: never;
        /** Link Task Consumable */
        post: operations["link_task_consumable_tasks__task_id__consumables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-consumables/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink Task Consumable */
        delete: operations["unlink_task_consumable_task_consumables__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homes/{home_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_homes__home_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaCreate */
        AreaCreate: {
            /** Name */
            name: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order?: number;
        };
        /** AreaRead */
        AreaRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Id
             * Format: uuid
             */
            home_id: string;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AreaUpdate */
        AreaUpdate: {
            /** Name */
            name?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** ConsumableCreate */
        ConsumableCreate: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Sku */
            sku?: string | null;
            /** Brand */
            brand?: string | null;
            /** Size */
            size?: string | null;
            /**
             * Quantity On Hand
             * @default 0
             */
            quantity_on_hand?: number;
            /**
             * Reorder Threshold
             * @default 0
             */
            reorder_threshold?: number;
            /** Preferred Vendor */
            preferred_vendor?: string | null;
            /** Reorder Url */
            reorder_url?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ConsumableRead */
        ConsumableRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Id
             * Format: uuid
             */
            home_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Sku */
            sku: string | null;
            /** Brand */
            brand: string | null;
            /** Size */
            size: string | null;
            /** Quantity On Hand */
            quantity_on_hand: number;
            /** Reorder Threshold */
            reorder_threshold: number;
            /** Preferred Vendor */
            preferred_vendor: string | null;
            /** Reorder Url */
            reorder_url: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConsumableUpdate */
        ConsumableUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Sku */
            sku?: string | null;
            /** Brand */
            brand?: string | null;
            /** Size */
            size?: string | null;
            /** Quantity On Hand */
            quantity_on_hand?: number | null;
            /** Reorder Threshold */
            reorder_threshold?: number | null;
            /** Preferred Vendor */
            preferred_vendor?: string | null;
            /** Reorder Url */
            reorder_url?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** Dashboard */
        Dashboard: {
            /** Home Id */
            home_id: string;
            /** Home Name */
            home_name: string;
            /** Home Health Score */
            home_health_score: number;
            counts: components["schemas"]["DashboardCounts"];
            /** Overdue */
            overdue: components["schemas"]["TaskRead"][];
            /** Due Soon */
            due_soon: components["schemas"]["TaskRead"][];
            /** Upcoming */
            upcoming: components["schemas"]["TaskRead"][];
            /** Needs Attention */
            needs_attention: components["schemas"]["DeviceRead"][];
            /** Low Stock */
            low_stock: components["schemas"]["ConsumableRead"][];
            /** Recently Completed */
            recently_completed: components["schemas"]["LogRead"][];
        };
        /** DashboardCounts */
        DashboardCounts: {
            /** Overdue */
            overdue: number;
            /** Due Soon */
            due_soon: number;
            /** Upcoming */
            upcoming: number;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /** Name */
            name: string;
            /** @default Other */
            device_type?: components["schemas"]["DeviceType"];
            /** Room Id */
            room_id?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Install Date */
            install_date?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Warranty End Date */
            warranty_end_date?: string | null;
            /** @default active */
            status?: components["schemas"]["DeviceStatus"];
            /** Notes */
            notes?: string | null;
        };
        /** DeviceRead */
        DeviceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Id
             * Format: uuid
             */
            home_id: string;
            /** Room Id */
            room_id: string | null;
            /** Name */
            name: string;
            device_type: components["schemas"]["DeviceType"];
            /** Manufacturer */
            manufacturer: string | null;
            /** Model Number */
            model_number: string | null;
            /** Serial Number */
            serial_number: string | null;
            /** Install Date */
            install_date: string | null;
            /** Purchase Date */
            purchase_date: string | null;
            /** Warranty End Date */
            warranty_end_date: string | null;
            status: components["schemas"]["DeviceStatus"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Next Due */
            next_due?: string | null;
        };
        /**
         * DeviceStatus
         * @enum {string}
         */
        DeviceStatus: "active" | "watching" | "needs_service" | "retired";
        /**
         * DeviceType
         * @enum {string}
         */
        DeviceType: "HVAC" | "Water Treatment" | "Appliance" | "Plumbing" | "Electrical" | "Exterior" | "Garden" | "Safety" | "Network" | "Other";
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Name */
            name?: string | null;
            device_type?: components["schemas"]["DeviceType"] | null;
            /** Room Id */
            room_id?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Install Date */
            install_date?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Warranty End Date */
            warranty_end_date?: string | null;
            status?: components["schemas"]["DeviceStatus"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeCreate */
        HomeCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Timezone
             * @default America/New_York
             */
            timezone?: string;
        };
        /** HomeRead */
        HomeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /** Timezone */
            timezone: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HomeUpdate */
        HomeUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** LogCreate */
        LogCreate: {
            /** Title */
            title: string;
            /** Completed At */
            completed_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Cost Cents */
            cost_cents?: number | null;
            /** Performed By */
            performed_by?: string | null;
            /** Task Id */
            task_id?: string | null;
        };
        /** LogRead */
        LogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Id
             * Format: uuid
             */
            home_id: string;
            /** Device Id */
            device_id: string | null;
            /** Task Id */
            task_id: string | null;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Title */
            title: string;
            /** Notes */
            notes: string | null;
            /** Cost Cents */
            cost_cents: number | null;
            /** Performed By */
            performed_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "medium" | "high" | "critical";
        /**
         * RecurrenceType
         * @enum {string}
         */
        RecurrenceType: "none" | "daily" | "weekly" | "monthly" | "quarterly" | "yearly" | "seasonal" | "custom_days";
        /** RoomCreate */
        RoomCreate: {
            /** Name */
            name: string;
            /** Area Id */
            area_id?: string | null;
            /** Room Type */
            room_type?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** RoomRead */
        RoomRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Id
             * Format: uuid
             */
            home_id: string;
            /** Area Id */
            area_id: string | null;
            /** Name */
            name: string;
            /** Room Type */
            room_type: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RoomUpdate */
        RoomUpdate: {
            /** Name */
            name?: string | null;
            /** Area Id */
            area_id?: string | null;
            /** Room Type */
            room_type?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * TaskCompletion
         * @description Payload sent when completing a maintenance task.
         */
        TaskCompletion: {
            /** Completed At */
            completed_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Cost Cents */
            cost_cents?: number | null;
            /** Performed By */
            performed_by?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Deduct Inventory
             * @default true
             */
            deduct_inventory?: boolean;
        };
        /** TaskCompletionResult */
        TaskCompletionResult: {
            task: components["schemas"]["TaskRead"];
            log: components["schemas"]["LogRead"];
        };
        /** TaskConsumableCreate */
        TaskConsumableCreate: {
            /**
             * Consumable Id
             * Format: uuid
             */
            consumable_id: string;
            /**
             * Quantity Required
             * @default 1
             */
            quantity_required?: number;
        };
        /** TaskConsumableRead */
        TaskConsumableRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Consumable Id
             * Format: uuid
             */
            consumable_id: string;
            /** Quantity Required */
            quantity_required: number;
            consumable: components["schemas"]["ConsumableRead"];
        };
        /** TaskCreate */
        TaskCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default other */
            task_type?: components["schemas"]["TaskType"];
            /** @default medium */
            priority?: components["schemas"]["Priority"];
            /** @default none */
            recurrence_type?: components["schemas"]["RecurrenceType"];
            /**
             * Recurrence Interval
             * @default 1
             */
            recurrence_interval?: number;
            /** Due Date */
            due_date?: string | null;
            /** Estimated Minutes */
            estimated_minutes?: number | null;
            /** Instructions */
            instructions?: string | null;
            /**
             * Requires Parts
             * @default false
             */
            requires_parts?: boolean;
            /**
             * Contractor Required
             * @default false
             */
            contractor_required?: boolean;
            /** @default active */
            status?: components["schemas"]["TaskStatus"];
        };
        /** TaskRead */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Id
             * Format: uuid
             */
            home_id: string;
            /** Device Id */
            device_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            task_type: components["schemas"]["TaskType"];
            priority: components["schemas"]["Priority"];
            recurrence_type: components["schemas"]["RecurrenceType"];
            /** Recurrence Interval */
            recurrence_interval: number;
            /** Due Date */
            due_date: string | null;
            /** Last Completed At */
            last_completed_at: string | null;
            /** Estimated Minutes */
            estimated_minutes: number | null;
            /** Instructions */
            instructions: string | null;
            /** Requires Parts */
            requires_parts: boolean;
            /** Contractor Required */
            contractor_required: boolean;
            status: components["schemas"]["TaskStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "active" | "paused" | "completed_once" | "archived";
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "replace_filter" | "inspect" | "clean" | "test" | "service" | "refill" | "winterize" | "other";
        /** TaskUpdate */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            task_type?: components["schemas"]["TaskType"] | null;
            priority?: components["schemas"]["Priority"] | null;
            recurrence_type?: components["schemas"]["RecurrenceType"] | null;
            /** Recurrence Interval */
            recurrence_interval?: number | null;
            /** Due Date */
            due_date?: string | null;
            /** Estimated Minutes */
            estimated_minutes?: number | null;
            /** Instructions */
            instructions?: string | null;
            /** Requires Parts */
            requires_parts?: boolean | null;
            /** Contractor Required */
            contractor_required?: boolean | null;
            status?: components["schemas"]["TaskStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_homes_homes_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_home_homes_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_homes__home_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_home_homes__home_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_home_homes__home_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_areas_homes__home_id__areas_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_area_homes__home_id__areas_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_area_areas__area_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                area_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_area_areas__area_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                area_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rooms_homes__home_id__rooms_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_homes__home_id__rooms_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_room_rooms__room_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_rooms__room_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_in_room_rooms__room_id__devices_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_homes__home_id__devices_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_in_home_homes__home_id__devices_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_device_tasks_devices__device_id__tasks_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_devices__device_id__tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_home_tasks_homes__home_id__tasks_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_endpoint_tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TaskCompletion"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCompletionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_device_logs_devices__device_id__logs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_log_devices__device_id__logs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_home_logs_homes__home_id__logs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consumables_homes__home_id__consumables_get: {
        parameters: {
            query?: {
                low_stock?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumableRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_consumable_homes__home_id__consumables_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumableCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consumable_consumables__consumable_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                consumable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_consumable_consumables__consumable_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                consumable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_consumable_consumables__consumable_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                consumable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumableUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_consumables_tasks__task_id__consumables_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConsumableRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_task_consumable_tasks__task_id__consumables_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskConsumableCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConsumableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_task_consumable_task_consumables__link_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_homes__home_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                home_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
